//
//  Workspace.swift
//  ProjectDescriptionHelpers
//
//  Created by Enes on 4/25/24.
//

import Foundation
import ProjectDescription
import ProjectDescriptionHelpers

// MARK: - Workspace

let workspace = Workspace(
    name: workspaceName,
    projects: [
        "\(workspaceName)/\(Module.featureA.rawValue)"
    ],
    generationOptions: .options(enableAutomaticXcodeSchemes: false, autogeneratedWorkspaceSchemes: .disabled)
)
